CREATE DATABASE mydb5;
USE mydb5;

CREATE TABLE Board
SELECT * FROM mydb4.Board;
CREATE TABLE Reply
SELECT * FROM mydb4.Reply;

ALTER TABLE Board 
MODIFY COLUMN id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE Reply
MODIFY COLUMN id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE Reply
ADD FOREIGN KEY (board_id) REFERENCES Board(id);

DESC Board;
DESC Reply;


CREATE TABLE Member(
Member_No INT(11) PRIMARY KEY AUTO_INCREMENT,
Member_ID VARCHAR(50),
Member_PW INT(11),
Member_Name VARCHAR(50),
Member_Date DATETIME,
Member_Sex VARCHAR(50),
Member_Email VARCHAR(50),
Member_Role VARCHAR(50),
Member_KaKao INT(11)
);
DESC Member;

